name: Flutter Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'

    - name: Core Flutter Setup & Version Fix
      run: |
        flutter config --no-analytics
        # अगर एंड्रॉइड फोल्डर नहीं है तो बनाएंगे
        if [ ! -d "android" ]; then
          flutter create --platforms=android --language=java --project-name=smart_emergency_sos .
        fi
        # ब्लूटूथ पैकेज के लिए minSdkVersion को जबरदस्ती 21 पर सेट करना
        sed -i 's/minSdkVersion .*/minSdkVersion 21/' android/app/build.gradle

    - name: Install dependencies
      run: |
        flutter pub get

    - name: Build APK
      run: |
        flutter build apk --release --no-pub

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SmartSOS-Release-APK
        path: build/app/outputs/flutter-apk/app-release.apk
    
