name: Flutter Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Core Flutter Setup
      run: |
        flutter config --no-analytics
        flutter create --platforms=android --project-name=smartsos .

    - name: Install dependencies
      run: |
        flutter pub get

    - name: Build APK
      env:
        # यह लाइन गिटहब को नए ग्रैडल रूल्स को ज़बरदस्ती लागू करने से रोकती है
        _JAVA_OPTIONS: "-Dandroid.newDsl=false"
      run: |
        flutter build apk --release --no-pub
        
